# Taps
tap "railwaycat/emacsmacport"

# Formulae
brew "bat"
brew "cabal-install"
brew "cdrtools"
brew "coreutils"
brew "exiftool"
brew "fastfetch"
brew "fd"
brew "findutils"
brew "forgejo-cli"
brew "fzf"
brew "ghc"
brew "git-filter-repo"
brew "gitleaks"
brew "helm"
brew "imagemagick"
brew "ispell"
brew "just"
brew "mas"
brew "mediainfo"
brew "mkcert"
brew "mpv"
brew "nixfmt"
brew "nmap"
brew "node"
brew "opentofu"
brew "pandoc"
brew "podman"
brew "podman-compose"
brew "poppler"
brew "pre-commit"
brew "resvg"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "skopeo"
brew "sshuttle"
brew "trufflehog"
brew "virt-manager"
brew "wakeonlan"
brew "wget"
brew "yt-dlp"
brew "zsh-autosuggestions"
brew "zsh-completions"

# Casks
cask "balenaetcher"
cask "betterdisplay"
cask "caffeine"
cask "claude-code@latest"
cask "claudebar"
cask "cyberduck"
cask "discord"
cask "emacs-mac"
cask "font-noto-nerd-font"
cask "iterm2"
cask "jagex"
cask "keka"
cask "kitlangton-hex"
cask "lm-studio"
cask "moonlight"
cask "onlyoffice"
cask "parsec"
cask "podman-desktop"
cask "raspberry-pi-imager"
cask "runelite"
cask "signal"
cask "syncthing-app"
cask "tailscale-app"
cask "ungoogled-chromium"
cask "wifiman"

# Mac App Store
mas "Parcel", id: 375589283
mas "Pixelmator Pro", id: 1289583905
mas "Bitwarden", id: 1352778147
mas "Windows App", id: 1295203466
mas "2FAS - Two Factor Authentication", id: 6443941139
mas "Karakeep", id: 6479258022
mas "uBlock Origin Lite", id: 6745342698
mas "Vimari", id: 1480933944
