---
- name: Create config directory
  ansible.builtin.file:
    group: "{{ group }}"
    mode: "0755"
    owner: "{{ username }}"
    path: "~/.config/yazi"
    state: directory
- name: Alias ranger to yazi
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    regexp: "^alias ranger="
    line: "alias ranger=yazi"
    mode: "0664"
    create: true
    state: present
