---
first_name: "Alex"
username: alex
group: alex
full_name: "Alex Taylor"
email: "ataylor@posteo.us"
carddav_address_book: "card"
personal_email: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/personal_email') }}"
personal_email_hostname: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/personal_email_hostname') }}"
personal_email_imap_domain: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/personal_email_imap_domain') }}"
carddav_url: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/carddav_url') }}"
carddav_username: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/carddav_username') }}"
caldav_url: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/caldav_url') }}"
caldav_username: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/caldav_username') }}"
freshrss_domain: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/freshrss_domain') }}"
freshrss_username: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/freshrss_username') }}"
hypervisor_mac_address: "{{ lookup('community.general.passwordstore', 'Repositories/client-infra/hypervisor_mac_address') }}"
personal_mail_pass_command: "pass personal_mail"
freshrss_pass_command: "pass freshrss"
vdirsyncer_calendar_pass_command: "\"pass\", \"vdirsyncer_calendar\""
