---
- name: Create ssh directory
  ansible.builtin.file:
    group: "{{ group }}"
    mode: "0700"
    owner: "{{ username }}"
    path: "~/.ssh"
    state: directory
- name: Configure ssh/config
  ansible.builtin.blockinfile:
    path: "~/.ssh/config"
    block: |
      Host *
          UseKeychain yes
          AddKeysToAgent yes
    create: true
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0600"
- name: Create gnupg directory
  ansible.builtin.file:
    group: "{{ group }}"
    mode: "0700"
    owner: "{{ username }}"
    path: "~/.gnupg"
    state: directory
- name: Configure gpg.conf
  ansible.builtin.lineinfile:
    path: "~/.gnupg/gpg.conf"
    line: "use-agent"
    mode: "0600"
    create: true
    state: present
- name: Configure gpg-agent.conf
  ansible.builtin.lineinfile:
    path: "~/.gnupg/gpg-agent.conf"
    line: "pinentry-program /opt/homebrew/bin/pinentry-mac"
    mode: "0600"
    create: true
    state: present
